package bilotta.jogodavelha;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */

public class TelaJogoDaVelha extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogoDaVelha
     */
    public TelaJogoDaVelha() {
        initComponents();
        panJogo.setVisible(false);
        panJogadores.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sptCabecalho = new javax.swing.JSeparator();
        panJogo = new java.awt.Panel();
        panJogadores = new java.awt.Panel();
        lblJogador1 = new javax.swing.JLabel();
        lblNomeJogador1 = new javax.swing.JLabel();
        lblNomeJogador2 = new javax.swing.JLabel();
        lblJogador2 = new javax.swing.JLabel();
        panBotoes = new java.awt.Panel();
        btnSair = new javax.swing.JButton();
        btnNovoJogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(sptCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 680, -1));

        panJogo.setBackground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout panJogoLayout = new javax.swing.GroupLayout(panJogo);
        panJogo.setLayout(panJogoLayout);
        panJogoLayout.setHorizontalGroup(
            panJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        panJogoLayout.setVerticalGroup(
            panJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(panJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 680, 450));

        panJogadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJogador1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJogador1.setForeground(new java.awt.Color(255, 51, 51));
        lblJogador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogador1.setText("JOGADOR 1");
        panJogadores.add(lblJogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblNomeJogador1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNomeJogador1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panJogadores.add(lblNomeJogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 300, 30));

        lblNomeJogador2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNomeJogador2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panJogadores.add(lblNomeJogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 330, 30));

        lblJogador2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJogador2.setForeground(new java.awt.Color(255, 51, 51));
        lblJogador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogador2.setText("JOGADOR 2");
        panJogadores.add(lblJogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        getContentPane().add(panJogadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 100));

        panBotoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setBackground(new java.awt.Color(255, 51, 51));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        panBotoes.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 170, 70));

        btnNovoJogo.setBackground(new java.awt.Color(51, 204, 0));
        btnNovoJogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNovoJogo.setText("NOVO JOGO");
        btnNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoJogoActionPerformed(evt);
            }
        });
        panBotoes.add(btnNovoJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 170, 70));

        getContentPane().add(panBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 680, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int saidaDoJogo = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do jogo?", "ENCERRAR JOGO", JOptionPane.YES_NO_OPTION);
        if (saidaDoJogo == 0) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoJogoActionPerformed
        panBotoes.setVisible(false);
        panJogadores.setVisible(true);
        Game game = new Game();
        lblNomeJogador1.setText(game.getJogador1().getNome());
        lblNomeJogador2.setText(game.getJogador2().getNome());
        panJogo.setLayout(null);
        panJogo.add(game.getTabuleiro());
        List<CampoTabuleiro> camposTabuleiro = new ArrayList<>();
        camposTabuleiro = game.getTabuleiro().criarCamposTabuleiro();
        panJogo.setVisible(true);
        
             
        
    }//GEN-LAST:event_btnNovoJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogoDaVelha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoJogo;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblJogador1;
    private javax.swing.JLabel lblJogador2;
    private javax.swing.JLabel lblNomeJogador1;
    private javax.swing.JLabel lblNomeJogador2;
    private java.awt.Panel panBotoes;
    private java.awt.Panel panJogadores;
    private java.awt.Panel panJogo;
    private javax.swing.JSeparator sptCabecalho;
    // End of variables declaration//GEN-END:variables
}
